headers = {
    'Accept': 'application/json,text/plain,*/*',
    'Accept-Language': 'en-US',
    "Accept-Encoding": "gzip, deflate",
    'Origin': 'https://app.paws.community',
    'Referer': 'https://app.paws.community/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'X-Requested-With': "org.telegram.messenger",
    'Sec-Ch-Ua': '"Chromium";v="130", "Android WebView";v="130", "Not?A_Brand";v="99"',
    'Sec-Ch-Aa-Mobile': "?1",
    'Sec-Ch-Ua-platform': '"Android"',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36',
}
